export const bioData = [
  {
    name: 'Robert Dannenberg',
    email: 'rmdberg1@gmail.com',
    info: 'Rob is an independent consultant on geopolitical and security risk. From 2009-2014 he was a managing director and head of the Office of Global Security for Goldman Sachs. Prior to joining the firm, Rob worked at BP plc, where he was the director of International Security Affairs. Before that, he worked for the Central Intelligence Agency for 24 years, where he served in several senior leadership positions, including Chief of Operations for the Counter Terrorism Center, Chief of the Central Eurasia Division and Chief of the CIA’s Information Operations Center. He is a recipient of the Distinguished Career Intelligence Medal, the Donovan Award for Operational Excellence, the George HW Bush Award for Excellence in Counter Terrorism and the Director’s Award. Rob is a member of the Board of Advisors to the Director of the National Counter-Terrorism Center and the Board of Directors of Business Executives for National Security. Rob earned a BA in International Relations from the University of Colorado and engaged in post-graduate study in Economics and Foreign Affairs at George Mason and Georgetown Universities.'
  },
  {
    name: 'Michael Sulick',
    email: 'michael.sulick@gmail.com',
    info: 'Dr. Michael Sulick was the Director of CIA\'s National Clandestine Service responsible for managing and coordinating  America\'s worldwide espionage operations. Prior to that he was director of CIA\'s counterintelligence and director of intelligence operations for Russia, Eurasia and Eastern Europe. He served overseas conducting and leading espionage operations in Russia, Eastern Europe, Asia and Latin America. Since retirement he has been a consultant to various US and foreign corporations on global risk and security issues, including JP Morgan Chase, Goldman Sachs, PriceWaterhouseCoopers and companies in Eastern Europe. He has also been a consultant on security issues to the Department of Homeland Security and Lawrence Livermore National Laboratory.  Dr. Sulick has also lectured on intelligence and international affairs at various universities and is the author of two books on American espionage. A native of New York City, Mr. Sulick received a Ph.D. from the City University of New York and a BA and MA in Russian Studies from Fordham University. He also served in Vietnam with the US Marine Corps.'
  },
  {
    name: 'Michael Morgan',
    email: 'mmorg721@gmail.com',
    info: 'Mr. Morgan began his professional career in 1978 at Chemical Bank International in New York City where he worked on Brazilian correspondent banking accounts until joining the CIA as an Operations Officer in 1980.  Over the ensuing 26 years, he served in 7 countries in Latin America, Europe and the former Soviet Union, to include senior field representative in Denmark and Mexico.  During postings in Washington, Mr. Morgan held senior positions focused on the Middle East, former Soviet Union and counterproliferation of weapons of mass destruction.  In 2005, Mr. Morgan was appointed Assistant Deputy Director within the newly formed Office of the Director of National Intelligence, where he had responsibility for oversight of all intelligence community human intelligence programs.  Upon retirement, Mr. Morgan joined the Raytheon Company as Director of Strategy in the company’s Intelligence and Information Systems business, where he was asked to manage a CEO-directed research and development program spanning all aspects of Raytheon’s business operations, to include assisting in the creation of Raytheon’s Information Assurance business.  In 2009, he joined the then newly formed Political Risk and Security team at PricewaterhouseCoopers International responsible for identifying, assessing and mitigating external risks to PwC’s business operations worldwide.  As Managing Director and Chief Security Officer until his retirement in 2018, Mr. Morgan had overall responsibility for the security of more than 250k partners and staff, as well as physical assets in 163 countries.  He also directly reported to the Global Chairman and his leadership team on a wide range of geopolitical issues. Mr. Morgan holds a BA in Government from Dartmouth College and lives in New London, New Hampshire.'
  },
  {
    name: 'David Bridges',
    email: 'almatinskaya@yahoo.com',
    info: 'David Bridges is the senior geopolitical and security analyst at Fidelity Management and Research Company (FMRCo), the investment advisor for Fidelity\'s family of mutual funds.  In this role, David provides expert geopolitical assessment to Fidelity investors. Prior to joining Fidelity in 2012, David served a 25-year career in the Central Intelligence Agency\'s (CIA) Clandestine Service.  David retired from CIA in 2011.  At the time of his retirement, he was a member of the Senior Intelligence Service, the elite leadership team that guides CIA activities across the globe.  Over the course of his career, David held a number of critical positions, to include executive oversight of all CIA activity in Russia, the former Soviet Union, central and eastern Europe, and the Balkans, operational coordination of all CIA offensive and defensive counterintelligence operations worldwide, and several assignments as chief of station.  In recognition of his outstanding work, he received CIA\'s Distinguished Career Intelligence Medal, the George Bush Award for Excellence in Counterterrorism, and the Clandestine Service\'s Donovan Award.  Prior to joining CIA, David spent five years working for a peacekeeping force in the Middle East.  He has been in the investments industry since 2012. David earned his bachelor\'s degree with high honors from Dartmouth college and his master\'s degree from the University of Chicago\'s Center for Middle Eastern Studies.  He speaks five languages.'
  },
  {
    name: 'Paul Kolbe',
    email: 'prkolbe@mac.com',
    info: 'Paul Kolbe has a distinguished record of service and accomplishment in public and private sectors. He currently leads BP’s Global Intelligence team which supports an intelligence led strategy for threat warning, risk mitigation, and crisis response. His team provides Geo-Political Threat Intelligence, strategic Cyber Intelligence and Business Intelligence to executive leadership, security networks and global business units. In this role he has developed deep expertise in energy sector geopolitics and security. Prior to joining BP, Paul served 25 years as an operations officer in the CIA’s clandestine service. He retired as Chief, Central Eurasia Division, responsible for global Russian operations as well as activities in Central Asia, the Caucasus and Eastern Europe. He served as Chief of Station, was a member of the Senior Intelligence Service and was awarded the Intelligence Medal of Merit and the Distinguished Career Intelligence Medal. Paul’s overseas assignments included tours in Russia, the Balkans, Indonesia, East Germany, Zimbabwe, and Austria. Paul has taught the graduate course “Intelligence for the Private Sector” at George Washington University’s Elliot School of International Relations. He is a board member of Business Executives for National Security and serves on the Security Advisory Board the for Eleanor Cook Foundation, a non-profit focused on food security in Africa. Paul has a degree in International Relations from Michigan State University and completed Thunderbird School of Management’s Advanced Oil and Gas Seminar.'
  }
];